stages:
  - generate
  - trigger
  - test

generator:
  stage: generate
  image: gitlab-registry.cern.ch/fastmachinelearning/hls4ml-testing:0.1.base
  tags: 
    - docker
  before_script:
    - source ~/.bashrc
    - git submodule init
    - git submodule update
    - conda activate hls4ml-testing
    - pip install .
  script: 
    - cd test/pytest
    - python generate_ci_yaml.py
  artifacts:
    paths:
      - test/pytest/pytests.yml

pytests:
  stage: trigger
  trigger:
    include:
      - artifact: test/pytest/pytests.yml
        job: generator
    strategy: depend